test_that("Test missing_count", {
  x <- missing_count(c(1,2,3))
  expect_true(is.numeric(x))
  expect_true(length(x)==1)
  expect_equal(x, 0)
  y <-  missing_count(c(NA, 1, NA, "NULL", ""))
  expect_true(is.numeric(y))
  expect_true(length(y)==1)
  expect_equal(y, 4)
})
